### ISSUE TITLE
Callysto name is too similar to existing project

### ISSUE THREAD

**Issue by dsblank** [ajmazurie/Callysto#1]
Hi, interesting project! Just pointing out that your name is too similar to an existing project (and organization) that does similar things: https://github.com/Calysto

This will surely cause confusion for our projects.

**Comment by dsblank** [comment]
Looking more closely at your kernels, you could build on top of Calysto's MetaKernel, and all of your kernels could have magics, too. And they could be run in parallel. Many other possibilities.

Perhaps you would be interested in joining our project?

**Comment by ajmazurie** [comment]
Thanks for pointing me to your project! I was looking for a moon of Jupiter when naming ours, one that would contain an 'i' I could change to 'y' as in Jupyter. I overlooked the fact that other projects may have a similar name... I guess I wasn't that original.

MetaKernel is indeed similar to Callysto's idea of creating a framework for Python-based kernels for Jupyter. The focus (from my initial exploration of MetaKernel's project page) is a bit different, though. I'll need to see if we would gain in joining your project.

Best, Aurélien
